name: Cheking code style

on:
  push:
    branches: [ master, develop, release, hotfix ]
  pull_request:
    branches: [ master, develop, release, hotfix ]


jobs:
  style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements/style.txt
    - name: Checking style
      run: |
        black ./heliotrope --check
        isort ./heliotrope --check --profile=black
