name: Python test

on:
  push:
    branches: [ master, develop, release, hotfix ]
  pull_request:
    branches: [ master, develop, release, hotfix ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      IS_TEST: "True"
      DB_URL: "mysql://root:test@127.0.0.1/test_heliotrope"
      MONGO_DB_URL: "mongodb://root:test@127.0.0.1"
    services:
      mariadb:
        image: mariadb
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: test_heliotrope
        ports:
          - 127.0.0.1:3306:3306
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: test
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Make MongoDB collection
        run: |
          mongo -u root -p test --eval "db.getSiblingDB('hitomi').createCollection('info')"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Temp Task
        run: |
          pip uninstall -y tortoise-orm
          pip install -U git+https://github.com/SaidBySolo/tortoise-orm@patch-1 
      - name: Run tests
        run: |
          pytest --cov=heliotrope --cov-report=xml
      - name: Codecov
        uses: codecov/codecov-action@v1
        